# Generated by Django 3.2 on 2021-11-01 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercaderias', '0002_alter_mercaderia_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mercaderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercaderias.mercaderia')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercaderias.unidad')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
    ]
