# Generated by Django 3.2 on 2022-05-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='unidad',
        ),
    ]
