# Generated by Django 3.2 on 2022-06-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_detalleventa_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pagado',
            field=models.BooleanField(default=True),
        ),
    ]
