# Generated by Django 3.2 on 2022-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
