# Generated by Django 3.2 on 2021-11-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercaderia',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
