# Generated by Django 3.2 on 2022-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0002_alter_mercaderia_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercaderia',
            name='minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
