# Generated by Django 3.2 on 2022-08-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0004_remove_mercaderia_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercaderia',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
