# Generated by Django 3.2.3 on 2022-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0005_mercaderia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercaderia',
            name='descripcion',
            field=models.TextField(unique=True),
        ),
    ]
