# Generated by Django 3.2 on 2024-12-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0006_alter_mercaderia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercaderia',
            name='pieza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
